// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqnajhoesbfyhtaghlqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxbmFqaG9lc2JmeWh0YWdobHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzAwNjcsImV4cCI6MjA1Njk0NjA2N30.DjON3_8dhZKlxpIrkqGn1L3lQLvNg9UeJ3eXUfQrSSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);